# docker-compose -f docker-compose-bc.yml up -d
version: '3'

services:
  sc-bc-01:
    image: nhdocker/sc-bc:latest
    container_name: "sc-bc-01"
    # deploy:
    #   replicas: 3
    #   update_config:
    #     parallelism: 2
    #     delay: 10s
    build:
      context: ./
      dockerfile: UwsgiDockerfile
      args:
        APP: "bc"
    restart: always
    volumes:
      - /home/dev/bc:/var/www/bc
      - /home/dev/bc/uwsgi/uwsgi01.ini:/var/www/uwsgi.ini:ro
      - /home/dev/bc/uwsgi/logs:/var/log/uwsgi
    # networks:
    #   - bc

  sc-bc-02:
    image: nhdocker/sc-bc:latest
    container_name: "sc-bc-02"
    # deploy:
    #   replicas: 3
    #   update_config:
    #     parallelism: 2
    #     delay: 10s
    build:
      context: ./
      dockerfile: UwsgiDockerfile
      args:
        APP: "bc"
    restart: always
    volumes:
      - /home/dev/bc:/var/www/bc
      - /home/dev/bc/uwsgi/uwsgi02.ini:/var/www/uwsgi.ini:ro
      - /home/dev/bc/uwsgi/logs:/var/log/uwsgi
    # networks:
    #   - bc

  sc-bc-03:
    image: nhdocker/sc-bc:latest
    container_name: "sc-bc-03"
    # deploy:
    #   replicas: 3
    #   update_config:
    #     parallelism: 2
    #     delay: 10s
    build:
      context: ./
      dockerfile: UwsgiDockerfile
      args:
        APP: "bc"
    restart: always
    volumes:
      - /home/dev/bc:/var/www/bc
      - /home/dev/bc/uwsgi/uwsgi03.ini:/var/www/uwsgi.ini:ro
      - /home/dev/bc/uwsgi/logs:/var/log/uwsgi
    # networks:
    #   - bc

  sc-bc-04:
    image: nhdocker/sc-bc:latest
    container_name: "sc-bc-04"
    # deploy:
    #   replicas: 3
    #   update_config:
    #     parallelism: 2
    #     delay: 10s
    build:
      context: ./
      dockerfile: UwsgiDockerfile
      args:
        APP: "bc"
    restart: always
    volumes:
      - /home/dev/bc:/var/www/bc
      - /home/dev/bc/uwsgi/uwsgi04.ini:/var/www/uwsgi.ini:ro
      - /home/dev/bc/uwsgi/logs:/var/log/uwsgi
    # networks:
    #   - bc

  sc-n-bc:
    image: nhdocker/sc-n-bc:latest
    container_name: "sc-n-bc"
    build:
      context: ./
      dockerfile: NginxDockerfile
    restart: always
    depends_on:
      - sc-bc-01
      - sc-bc-02
      - sc-bc-03
      - sc-bc-04
    volumes:
      - /home/dev/bc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/dev/bc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /home/dev/bc/nginx/logs:/root/logs
    ports:
      # - 80:80
      - 443:443
#     networks:
#       - bc

# networks:
#   bc:
#     driver: overlay